version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install cfn-lint taskcat
  pre_build:
    commands:
      - echo "Running cfn-lint..."
      - cfn-lint s3://nhom6-lab/main.yaml
  build:
    commands:
      - echo "Running Taskcat..."
      - taskcat test run
artifacts:
  files:
    - '**/*'
