AWSTemplateFormatVersion: '2010-09-09'
Description: "Template to create an S3 bucket"

Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 bucket"

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref nhom6-lab1
Outputs:
  BucketNameOutput:
    Description: "The name of the S3 bucket"
    Value: !Ref nhom6-lab1

